#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18408
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Ruly.Resource", IsApplication=true)]

namespace Ruly
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::Ruly.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::Ruly.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060001
			public const int place_array = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int state_array = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_accept = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_alarms = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_cancel = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_discard = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_edit = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_go_to_today = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_new = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_action_pause = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_action_play = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_action_save = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_action_settings = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_action_stop = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Icon = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090011
			public const int AlarmSwitch1 = 2131296273;
			
			// aapt resource value: 0x7f090013
			public const int AlarmSwitch2 = 2131296275;
			
			// aapt resource value: 0x7f090012
			public const int AlarmTime1 = 2131296274;
			
			// aapt resource value: 0x7f090014
			public const int AlarmTime2 = 2131296276;
			
			// aapt resource value: 0x7f090001
			public const int InboxTaskList = 2131296257;
			
			// aapt resource value: 0x7f09000e
			public const int LogBG = 2131296270;
			
			// aapt resource value: 0x7f090004
			public const int NextTaskList = 2131296260;
			
			// aapt resource value: 0x7f090010
			public const int RelativeLayout = 2131296272;
			
			// aapt resource value: 0x7f09000c
			public const int ShellActivityFrame = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int ShellFrame = 2131296269;
			
			// aapt resource value: 0x7f09000f
			public const int ShellView = 2131296271;
			
			// aapt resource value: 0x7f090008
			public const int TodayDate = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int TodayDay = 2131296265;
			
			// aapt resource value: 0x7f09000b
			public const int TodayHistoryList = 2131296267;
			
			// aapt resource value: 0x7f09000a
			public const int TodayTime = 2131296266;
			
			// aapt resource value: 0x7f090002
			public const int linearLayout1 = 2131296258;
			
			// aapt resource value: 0x7f090005
			public const int linearLayout2 = 2131296261;
			
			// aapt resource value: 0x7f090007
			public const int linearLayout3 = 2131296263;
			
			// aapt resource value: 0x7f090028
			public const int menu_add = 2131296296;
			
			// aapt resource value: 0x7f090030
			public const int menu_alarm = 2131296304;
			
			// aapt resource value: 0x7f090027
			public const int menu_discard = 2131296295;
			
			// aapt resource value: 0x7f09002a
			public const int menu_edit = 2131296298;
			
			// aapt resource value: 0x7f09002e
			public const int menu_finish = 2131296302;
			
			// aapt resource value: 0x7f09002b
			public const int menu_go = 2131296299;
			
			// aapt resource value: 0x7f090031
			public const int menu_history = 2131296305;
			
			// aapt resource value: 0x7f09002f
			public const int menu_new = 2131296303;
			
			// aapt resource value: 0x7f09002c
			public const int menu_pause = 2131296300;
			
			// aapt resource value: 0x7f09002d
			public const int menu_resume = 2131296301;
			
			// aapt resource value: 0x7f090029
			public const int menu_save = 2131296297;
			
			// aapt resource value: 0x7f090032
			public const int menu_settings = 2131296306;
			
			// aapt resource value: 0x7f090015
			public const int taskAlarmDateTime = 2131296277;
			
			// aapt resource value: 0x7f090018
			public const int taskAlarmList = 2131296280;
			
			// aapt resource value: 0x7f090025
			public const int taskCreated = 2131296293;
			
			// aapt resource value: 0x7f090019
			public const int taskEditHome = 2131296281;
			
			// aapt resource value: 0x7f09001a
			public const int taskHistoryFrom = 2131296282;
			
			// aapt resource value: 0x7f09001c
			public const int taskHistoryName = 2131296284;
			
			// aapt resource value: 0x7f09001b
			public const int taskHistoryTo = 2131296283;
			
			// aapt resource value: 0x7f09001d
			public const int taskInfoList = 2131296285;
			
			// aapt resource value: 0x7f090026
			public const int taskModified = 2131296294;
			
			// aapt resource value: 0x7f090017
			public const int taskNote = 2131296279;
			
			// aapt resource value: 0x7f090024
			public const int taskParent = 2131296292;
			
			// aapt resource value: 0x7f090023
			public const int taskPlace = 2131296291;
			
			// aapt resource value: 0x7f090022
			public const int taskState = 2131296290;
			
			// aapt resource value: 0x7f090016
			public const int taskTitle = 2131296278;
			
			// aapt resource value: 0x7f090003
			public const int textView1 = 2131296259;
			
			// aapt resource value: 0x7f09001e
			public const int textView2 = 2131296286;
			
			// aapt resource value: 0x7f09001f
			public const int textView3 = 2131296287;
			
			// aapt resource value: 0x7f090020
			public const int textView4 = 2131296288;
			
			// aapt resource value: 0x7f090021
			public const int textView5 = 2131296289;
			
			// aapt resource value: 0x7f090006
			public const int toggleAbstDetail = 2131296262;
			
			// aapt resource value: 0x7f090000
			public const int viewPagerHome = 2131296256;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainInbox = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainNext = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainToday = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ShellActivity = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ShellFragment = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int TaskAlarm = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int TaskEdit = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int TaskEditHome = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int TaskHistoryItem = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int TaskInfo = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int TaskItem = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int TaskItemDetail = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int edit_menu = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int info_menu = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int main_menu = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int shell_menu = 2131230723;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int hello = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int MyActionBar = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int MyTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int preferences = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
