#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34003
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Ruly.Resource", IsApplication=true)]

namespace Ruly
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::Ruly.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::Ruly.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int place_array = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int state_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_accept = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_cancel = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_collapse = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_discard = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_edit = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_expand = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_new = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_action_pause = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_action_play = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_action_save = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_action_stop = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Icon = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080001
			public const int InboxTaskList = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int NextTaskList = 2131230724;
			
			// aapt resource value: 0x7f08000c
			public const int ShellFrame = 2131230732;
			
			// aapt resource value: 0x7f080008
			public const int TodayDate = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int TodayDay = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int TodayHistoryList = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int TodayTime = 2131230730;
			
			// aapt resource value: 0x7f080002
			public const int linearLayout1 = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int linearLayout2 = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int linearLayout3 = 2131230727;
			
			// aapt resource value: 0x7f080020
			public const int menu_add = 2131230752;
			
			// aapt resource value: 0x7f08001f
			public const int menu_discard = 2131230751;
			
			// aapt resource value: 0x7f080022
			public const int menu_edit = 2131230754;
			
			// aapt resource value: 0x7f080026
			public const int menu_finish = 2131230758;
			
			// aapt resource value: 0x7f080023
			public const int menu_go = 2131230755;
			
			// aapt resource value: 0x7f080027
			public const int menu_new = 2131230759;
			
			// aapt resource value: 0x7f080024
			public const int menu_pause = 2131230756;
			
			// aapt resource value: 0x7f080025
			public const int menu_resume = 2131230757;
			
			// aapt resource value: 0x7f080021
			public const int menu_save = 2131230753;
			
			// aapt resource value: 0x7f08000d
			public const int taskAlarmDateTime = 2131230733;
			
			// aapt resource value: 0x7f080010
			public const int taskAlarmList = 2131230736;
			
			// aapt resource value: 0x7f08001d
			public const int taskCreated = 2131230749;
			
			// aapt resource value: 0x7f080011
			public const int taskEditHome = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int taskHistoryFrom = 2131230738;
			
			// aapt resource value: 0x7f080014
			public const int taskHistoryName = 2131230740;
			
			// aapt resource value: 0x7f080013
			public const int taskHistoryTo = 2131230739;
			
			// aapt resource value: 0x7f080015
			public const int taskInfoList = 2131230741;
			
			// aapt resource value: 0x7f08001e
			public const int taskModified = 2131230750;
			
			// aapt resource value: 0x7f08000f
			public const int taskNote = 2131230735;
			
			// aapt resource value: 0x7f08001c
			public const int taskParent = 2131230748;
			
			// aapt resource value: 0x7f08001b
			public const int taskPlace = 2131230747;
			
			// aapt resource value: 0x7f08001a
			public const int taskState = 2131230746;
			
			// aapt resource value: 0x7f08000e
			public const int taskTitle = 2131230734;
			
			// aapt resource value: 0x7f080003
			public const int textView1 = 2131230723;
			
			// aapt resource value: 0x7f080016
			public const int textView2 = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int textView3 = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int textView4 = 2131230744;
			
			// aapt resource value: 0x7f080019
			public const int textView5 = 2131230745;
			
			// aapt resource value: 0x7f080006
			public const int toggleAbstDetail = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int viewPagerHome = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainInbox = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainNext = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainToday = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ShellActivity = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TaskAlarm = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int TaskEdit = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int TaskEditHome = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int TaskHistoryItem = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int TaskInfo = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int TaskItem = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int TaskItemDetail = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int edit_menu = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int info_menu = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int main_menu = 2131165186;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int hello = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int MyActionBar = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int MyTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
